### ISSUE TITLE
Morning session: Peer-to-peer code review (March 21)

### ISSUE THREAD

**Issue by Tessyrich** [Alejandroq12/my-books#3]

**Comment by Tessyrich** [comment]
Hello @Alejandroq12 
Thank you for sharing your code with us. 

After examining your code we can say you did a good job!

### HIGHLIGHTS

- Very clean code
- Use of semantic HTML
- JavaScript best practices

### SUGGESTIONS
While iterating through the list of books, I suggest you use forEach instead of the conventional For loop as the previous is more professional and also is among Javascript best practices.

**Comment by Alejandroq12** [comment]
Hello! Thank you very much for your feedback.
I modified the for loop and, following your recommendation, I utilized forEach.
Have a good day.
